services:
  database:
    container_name: drb_local_db
    volumes:
      - drb_local_dbdata:/var/lib/postgresql/data
    image: postgres:16.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: localpsql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"] # pg_ready never needs a password, postgres user simply prevents log message telling us default root user does not exist
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  elasticsearch:
    container_name: drb_local_es
    # use same ES version as in QA/Prod servers
    image: elasticsearch:7.17.28
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elastic
    command:
      - /bin/sh
      - -c
      - elasticsearch-plugin install analysis-icu analysis-smartcn analysis-kuromoji analysis-stempel; /usr/local/bin/docker-entrypoint.sh elasticsearch
    volumes:
      - drb_local_esdata:/bitnami/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  redis:
    container_name: drb_local_rs
    image: redis:7.0
    ports:
      - 6379:6379
    volumes:
      - drb_local_rsdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    container_name: drb_local_api
    depends_on:
      - database
      - elasticsearch
    build:
      context: .
    command: -e local-compose -p APIProcess
    ports:
      # TODO: this port spec should read from the local env files
      - 5050:5050
    volumes:
      - type: bind
        source: .
        target: /src
        read_only: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5050/apidocs/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  aws_services:
    container_name: drb-local-aws
    image: localstack/localstack:latest
    environment:
      - DEBUG=1
      - LOCALSTACK_HOSTNAME=localhost
      - TEST_AWS_ACCOUNT_ID=000000000000
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix://var/run/docker.sock
    ports:
      - "4566:4566"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/init-localstack-resources.sh:/etc/localstack/init/ready.d/init-localstack-resources.sh
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4566/_localstack/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  devsetup:
    container_name: drb_local_devSetUp
    depends_on:
      database:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      aws_services:
        condition: service_healthy
    build:
      context: .
    command: -e local-compose -p LocalDevelopmentSetupProcess
    volumes:
      # this overrides `ADD . /src` in the DockerFile, mapping the \
      # current local filesystem to "/src" in the docker image.
      - type: bind
        source: .
        target: /src
        read_only: true

volumes:
  drb_local_dbdata:
  drb_local_esdata:
  drb_local_mqdata:
  drb_local_rsdata:
