services:
  devsetup:
    extends:
      file: docker-compose.yml
      service: devsetup

  database:
    extends:
      file: docker-compose.yml
      service: database

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 2s
      timeout: 5s
      retries: 5

  redis:
    extends:
      file: docker-compose.yml
      service: redis

  s3:
    extends:
      file: docker-compose.yml
      service: s3

  seeddb:
    container_name: drb_local_seed
    depends_on:
      devsetup:
        condition: service_started
      database:
        condition: service_started
      elasticsearch:
        condition: service_started
      s3:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

    build:
      context: .
    command: -e local-compose -p SeedLocalDataProcess -i daily
    volumes:
      - type: bind
        source: .
        target: /src
        read_only: true

volumes:
  drb_local_dbdata:
  drb_local_esdata:
  drb_local_mqdata:
  drb_local_rsdata:
