ENVIRONMENT: xx

# POSTGRES CONNECTION DETAILS
POSTGRES_HOST: xxx
POSTGRES_PORT: xxx
POSTGRES_NAME: xxx 
POSTGRES_USER: xxx
POSTGRES_PSWD: xxx
POSTGRES_ADMIN_USER: xxx
POSTGRES_DB_USER: xxx

# REDIS CONFIGURATION
REDIS_HOST: xxx
REDIS_PORT: xxx

# ELASTICSEARCH CONFIGURATION
ELASTICSEARCH_INDEX: xxx
ELASTICSEARCH_HOST: xxx
ELASTICSEARCH_PORT: xxx
ELASTICSEARCH_TIMEOUT: xxx

# RABBITMQ CONFIGURATION
RABBIT_HOST: xxx
RABBIT_PORT: xxx
OCLC_QUEUE: xxx
FILE_QUEUE: xxx

# HATHITRUST CONFIGURATION

# OCLC CONFIGURATION
OCLC_API_KEY: xxx

# AWS CONFIGURATION
AWS_ACCESS: xxx 
AWS_SECRET: xxx 
AWS_REGION: xxx
FILE_BUCKET: xxx

# NYPL BIB REPLICA DB CONNECTION
NYPL_BIB_HOST: xxx
NYPL_BIB_PORT: xxx
NYPL_BIB_NAME: xxx

# NYPL Location Code Lookup
NYPL_LOCATIONS_BY_CODE: xxx

# NYPL API Credentials
NYPL_API_CLIENT_TOKEN_URL: xxx

# Bardo CCE API URL
BARDO_CCE_API: xxx

# Project MUSE MARC endpoint
MUSE_MARC_URL: xxx

# DOAB OAI-PMH endpoint
DOAB_OAI_URL: xxx

# ePub-to-Webpub Conversion Service
WEBPUB_CONVERSION_URL: xxx

# Allowed sources of CORS requests to proxy endpoint
API_PROXY_CORS_ALLOWED: (?:Source1:Source2)

# Current NYPL Webreader version
READER_VERSION: xxx
