# POSTGRES CONNECTION DETAILS
DB_HOST: xxx
DB_PORT: xxx
DB_NAME: xxx 
DB_USER: xxx
DB_PSWD: xxx
ADMIN_USER: xxx
DB_USER: xxx

# REDIS CONFIGURATION
REDIS_HOST: xxx
REDIS_PORT: xxx

# ELASTICSEARCH CONFIGURATION
ES_INDEX: xxx
ES_HOST: xxx
ES_PORT: xxx
ES_TIMEOUT: xxx

# RABBITMQ CONFIGURATION
RABBIT_HOST: xxx
RABBIT_PORT: xxx
OCLC_QUEUE: xxx
FILE_QUEUE: xxx

# HATHITRUST CONFIGURATION
HATHI_DATAFILES: https://www.hathitrust.org/filebrowser/download/244651

# OCLC CONFIGURATION
OCLC_API_KEY: xxx

# AWS CONFIGURATION
AWS_ACCESS: xxx 
AWS_SECRET: xxx 
AWS_REGION: xxx
FILE_BUCKET: xxx

# NYPL BIB REPLICA DB CONNECTION
BIB_HOST: xxx
BIB_PORT: xxx
BIB_NAME: xxx
BIB_USER: xxx
BIB_PSWD: xxx

# NYPL Location Code Lookup
NYPL_LOCATIONS_BY_CODE: xxx

# NYPL API Credentials
API_CLIENT_ID: xxx
API_CLIENT_SECRET: xxx
API_CLIENT_TOKEN_URL: xxx

# GITHUB API Credentials
GITHUB_API_KEY: xxx
GITHUB_API_ROOT: https://api.github.com/graphql

# Bardo CCE API URL
BARDO_CCE_API: xxx