LOG_LEVEL: INFO

POSTGRES_HOST: sfr-new-metadata-production-cluster.cluster-cvy7z512hcjg.us-east-1.rds.amazonaws.com
POSTGRES_NAME: dcdw_qa
POSTGRES_PORT: '5432'

REDIS_HOST: localhost
REDIS_PORT: '6379'

ELASTICSEARCH_INDEX: drb_dcdw_qa
ELASTICSEARCH_SCHEME: https
ELASTICSEARCH_HOST: vpc-drb-search-production-5ptfzwisshcadbbaph35dqilva.us-east-1.es.amazonaws.com
ELASTICSEARCH_PORT: '9200'
ELASTICSEARCH_TIMEOUT: '30'

READER_VERSION: 'v2'
API_PROXY_CORS_ALLOWED: '*'
