ENVIRONMENT: local

LOG_LEVEL: INFO

POSTGRES_HOST: localhost
POSTGRES_PORT: '5432'
POSTGRES_NAME: drb_test_db
POSTGRES_USER: localuser
POSTGRES_PSWD: localpsql
ADMIN_USER: postgres
ADMIN_PSWD: localpsql

REDIS_HOST: localhost
REDIS_PORT: '6379'

ELASTICSEARCH_INDEX: drb_test_index
ELASTICSEARCH_SCHEME: http
ELASTICSEARCH_HOST: localhost
ELASTICSEARCH_PORT: '9200'
ELASTICSEARCH_TIMEOUT: '30'
ELASTICSEARCH_USER: elastic
ELASTICSEARCH_PSWD: elastic

RABBIT_HOST: localhost
RABBIT_PORT: '5672'
RABBIT_USER: guest
RABBIT_PSWD: guest
RABBIT_VIRTUAL_HOST: ''
RABBIT_EXCHANGE: ''
OCLC_QUEUE: oclc_catalog
OCLC_ROUTING_KEY: oclc_catalog
FILE_QUEUE: drb_files
FILE_ROUTING_KEY: drb_files
RECORD_PIPELINE_QUEUE: records
RECORD_PIPEPELINE_ROUTING_KEY: records

AWS_REGION: us-east-1
FILE_BUCKET: drb-files-local
S3_ENDPOINT_URL: http://localhost:4566

OCLC_QUERY_LIMIT: '390000'

BARDO_CCE_API: http://sfr-c-ecsal-14v3injrieoy5-258691445.us-east-1.elb.amazonaws.com/search/

API_PROXY_CORS_ALLOWED: '*'

READER_VERSION: v2

NYPL_BIB_HOST: bib-service-production-rep.cvy7z512hcjg.us-east-1.rds.amazonaws.com
NYPL_BIB_NAME: bib_service_production
NYPL_BIB_PORT: '5432'
NYPL_LOCATIONS_BY_CODE: https://nypl-core-objects-mapping-qa.s3.amazonaws.com/by_sierra_location.json
NYPL_API_CLIENT_TOKEN_URL: https://isso.nypl.org/oauth/token

DRB_API_HOST: http://localhost:5050
DRB_API_URL: http://localhost:5050

DEFAULT_COVER_URL: https://drb-files-qa.s3.amazonaws.com/covers/default/defaultCover.png
