STAGE: production

LOG_LEVEL: info
 
POSTGRES_HOST: sfr-new-metadata-production-cluster.cluster-cvy7z512hcjg.us-east-1.rds.amazonaws.com
POSTGRES_NAME: dcdw_production
POSTGRES_PORT: '5432'

REDIS_PORT: '6379'

ELASTICSEARCH_TIMEOUT: '10'

RABBIT_HOST: rmq.aws.nypl.org
RABBIT_PORT: '5672'
RABBIT_VIRTUAL_HOST: /sfr
RABBIT_EXCHANGE: sfrIngestExchange
OCLC_QUEUE: sfrOCLCCatalog
OCLC_ROUTING_KEY: sfrOCLCCatalog
FILE_QUEUE: sfrS3Files
FILE_ROUTING_KEY: sfrS3Files

OCLC_QUERY_LIMIT: '390000'

NYPL_BIB_HOST: bib-service-production-rep.cvy7z512hcjg.us-east-1.rds.amazonaws.com
NYPL_BIB_NAME: bib_service_production
NYPL_BIB_PORT: '5432'

NYPL_LOCATIONS_BY_CODE: https://nypl-core-objects-mapping-production.s3.amazonaws.com/by_sierra_location.json

DRB_API_HOST: 'drb-api-production.nypl.org'
DRB_API_PORT: '80'

DEFAULT_COVER_URL: https://drb-files-production.s3.amazonaws.com/covers/default/defaultCover.png

API_PROXY_CORS_ALLOWED: http[s]?://.*nypl.org

READER_VERSION: v2

PUBLISHERS: "UofMichigan Press"
REFERRER_URL: "https://digital-research-books-beta.nypl.org/"

DOWNLOAD_BUCKET: "ump-pdf-repository-logs"
DOWNLOAD_LOG_PATH: "logs/946183545209/us-east-1/ump-pdf-repository/"

VIEW_BUCKET: "drb-files-production-logs"
VIEW_LOG_PATH: "logs/946183545209/us-east-1/drb-files-production"
