# POSTGRES CONNECTION DETAILS
# POSTGRES_USER, POSTGRES_PSWD, POSTGRES_ADMIN_USER and POSTGRES_ADMIN_PSWD must be configured in secrets file 
# POSTGRES_HOST: '' 
# POSTGRES_NAME: ''
# POSTGRES_PORT: ''

# REDIS CONFIGURATION
REDIS_HOST: 'shared-qa.frh6pg.0001.use1.cache.amazonaws.com'
REDIS_PORT: '6379'

# ELASTICSEARCH CONFIGURATION
# ELASTICSEARCH_INDEX, ELASTICSEARCH_HOST must be configured in secrets file
ELASTICSEARCH_PORT: '80'
ELASTICSEARCH_TIMEOUT: '30'

# RABBITMQ CONFIGURATION
# RABBIT_HOST: ''
# RABBIT_PORT: ''
OCLC_QUEUE: oclc_catalog
EPUB_QUEUE: epub_files

# HATHITRUST CONFIGURATION
HATHI_DATAFILES: https://www.hathitrust.org/filebrowser/download/244651

# OCLC CONFIGURATION
# OCLC_API_KEY must be configured in secrets file

# AWS CONFIGURATION
# AWS_ACCESS and AWS_SECRET must be configured in secrets file
AWS_REGION: 'us-east-1'
EPUB_BUCKET: 'sfr_files'

# NYPL BIB REPLICA DB CONNECTION
# NYPL_BIB_USER, NYPL_BIB_PSWD must be configured in secrets file
NYPL_BIB_HOST: 'bib-service-production-rep.cvy7z512hcjg.us-east-1.rds.amazonaws.com'
NYPL_BIB_NAME: 'bib_service_production'
NYPL_BIB_PORT: '5432'

# NYPL Location Code Lookup
NYPL_LOCATIONS_BY_CODE: https://nypl-core-objects-mapping-qa.s3.amazonaws.com/by_sierra_location.json

# NYPL API Credentials
# API_CLIENT_ID and API_CLIENT_SECRET must be configured in secrets file
NYPL_API_CLIENT_TOKEN_URL: https://isso.nypl.org/oauth/token

# GITHUB API Credentials
# GITHUB_API_KEY must be configured in secrets file
GITHUB_API_ROOT: https://api.github.com/graphql

# Bardo CCE API URL
BARDO_CCE_API: http://sfr-bardo-copyright-development.us-east-1.elasticbeanstalk.com/search

# Project MUSE MARC endpoint
MUSE_MARC_URL: https://about.muse.jhu.edu/lib/metadata?format=marc&content=book&include=oa&filename=open_access_books&no_auth=1

# DOAB OAI-PMH endpoint
DOAB_OAI_URL: http://www.doabooks.org/oai?
