# LOGGING
LOG_LEVEL: debug

# POSTGRES CONNECTION DETAILS
# POSTGRES_USER, POSTGRES_PSWD, POSTGRES_ADMIN_USER and POSTGRES_ADMIN_PSWD must be configured in secrets file 
POSTGRES_HOST: '127.0.0.1'
POSTGRES_NAME: dcdw_qa
POSTGRES_PORT: '9090'

# ELASTICSEARCH CONFIGURATION
# ELASTICSEARCH_INDEX, ELASTICSEARCH_HOST must be configured in secrets file
ELASTICSEARCH_PORT: '9091'
ELASTICSEARCH_TIMEOUT: '5'

# REDIS CONFIGURATION
# REDIS_HOST configured as part of ECS deployment
REDIS_PORT: '9092'

# Allowed sources of CORS requests to proxy endpoint
API_PROXY_CORS_ALLOWED: '*'

# Current NYPL Webreader version
READER_VERSION: v2
