services:
  drb-api:
    image: python:3.8
    default: true
    expose: 3000
    commands:
      build:
        - pip install -r requirements.txt
      start:
        - python main.py -p APIProcess -e qa
  drb-api-front:
    image: tugboat/node:14
    expose: 80
    commands:
      init:
        - git clone https://github.com/NYPL/sfr-bookfinder-front-end.git .
      build:
        - npm install
        - npm run build
      start:
        - npm start &
