services:
  drb-api:
    image: tugboatqa/python:3.9
    default: true
    expose: 3000
    commands:
      build:
        - pip install -r api-requirements.txt
      start:
        - python main.py -p APIProcess -e qa &
  drb-api-front:
    image: tugboat/node:14
    expose: 80
    commands:
      init:
        - git clone https://github.com/NYPL/sfr-bookfinder-front-end.git .
      build:
        - npm install
        - npm run build
      start:
        - npm start &
