services:
  drb-api:
    image: python:3.8
    default: true
    expose: 80
    commands:
      build:
        - pip install -r requirements.txt
      start:
        - python main.py -p APIProcess -e qa
