services:
  drb-api:
    image: tugboatqa/python:3.9
    default: true
    commands:
      build:
        - pip install -r api-requirements.txt
      start:
        - python main.py -p APIProcess -e qa &
