# POSTGRES CONNECTION DETAILS
DB_HOST: xxx
DB_PORT: xxx
DB_NAME: xxx 
DB_USER: xxx
DB_PSWD: xxx
ADMIN_USER: xxx
DB_USER: xxx

# REDIS CONFIGURATION
REDIS_HOST: xxx
REDIS_PORT: xxx

# ELASTICSEARCH CONFIGURATION
ES_INDEX: xxx
ES_HOST: xxx
ES_PORT: xxx
ES_TIMEOUT: xxx

# RABBITMQ CONFIGURATION
RABBIT_HOST: xxx
RABBIT_PORT: xxx
OCLC_QUEUE: xxx
EPUB_QUEUE: xxx

# HATHITRUST CONFIGURATION
HATHI_DATAFILES: https://www.hathitrust.org/filebrowser/download/244651

# OCLC CONFIGURATION
OCLC_API_KEY: xxx

# AWS CONFIGURATION
AWS_ACCESS: xxx 
AWS_SECRET: xxx 
AWS_REGION: xxx
EPUB_BUCKET: xxx
