name: Playwright Tests for DRB Web via BrowserStack
on:
  workflow_call:
    inputs:
      base_url:
        description: "Base URL for environment"
        default: "http://local.nypl.org:3000"
        required: false
        type: string

jobs:
  test:
    name: Playwright Tests for DRB Web via BrowserStack
    runs-on: ubuntu-latest
    steps:
      - name: BrowserStack Env Setup
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_PW }}
          project-name: NYPL DRB
          build-name: DRB Web Automated Tests

      - name: BrowserStack Local Tunnel Setup # set up tunnel connection between GitHub Actions runner environment and BrowserStack device cloud
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: Verify BrowserStack Local
        run: |
          # Wait longer for BrowserStackLocal to initialize
          sleep 15
          echo "Checking BrowserStack Local status..."
          curl -v http://bs-local.com:45691/check || echo "BrowserStackLocal not running"

      - name: Setup BrowserStackLocal manually
        run: |
          wget https://www.browserstack.com/browserstack-local/BrowserStackLocal-linux-x64.zip
          unzip BrowserStackLocal-linux-x64.zip
          ./BrowserStackLocal --key ${{ secrets.BROWSERSTACK_PW }} --force-local --verbose --local-identifier random &
          sleep 15
          ps aux | grep BrowserStackLocal

      - name: Verify BrowserStackLocal installation
        run: |
          find / -name BrowserStackLocal 2>/dev/null || echo "BrowserStackLocal not found"
          ps aux | grep -i browserstack

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "web/.nvmrc"
          cache: npm
          cache-dependency-path: "web/package-lock.json"

      - name: Set environment for branch
        working-directory: ./web
        run: |
          touch .env
          echo "BASE_URL=http://localhost:3000" >> .env
          echo "BASE_URL=${{ inputs.base_url }}"
        shell: bash

      # - name: Add hosts to /etc/hosts
      #   if: inputs.base_url == 'http://local.nypl.org:3000/'
      #   run: |
      #     echo "${{ inputs.base_url }}"
      #     sudo echo "127.0.0.1 local.nypl.org" | sudo tee -a /etc/hosts

      - name: Install dependencies
        working-directory: ./web
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: ./web
        run: npx playwright install --with-deps

      - name: Build app
        working-directory: ./web
        run: NODE_ENV=test npm run build

      - name: Start the app
        # if: inputs.base_url == 'http://local.nypl.org:3000/'
        working-directory: ./web
        run: |
          HOST=0.0.0.0 PORT=3000 NODE_ENV=test npm start &
          sleep 5
        shell: bash

      - name: Network diagnostics
        run: |
          echo "==== Testing connectivity ===="
          curl -v http://localhost:3000 || echo "Cannot connect to localhost:3000"
          netstat -tulpn | grep 3000
          ps aux | grep node

      - name: Run tests on BrowserStack
        id: run-tests
        working-directory: ./web
        run: npx browserstack-node-sdk playwright test
        continue-on-error: true

      - name: Set failure workflow status 🚨
        if: steps.run-tests.outcome != 'success'
        run: exit 1

      - name: Set successful workflow status ✅
        if: steps.run-tests.outcome == 'success'
        run: exit 0
