# This workflow runs tests against the deployed to QA API server

name: ETL Pipeline CI

on:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1

      - name: Mask secrets
        uses: ./.github/actions/mask-etl-pipeline-secrets

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: 'etl-pipeline/.python-version'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install GCC 12
        run: |
          sudo apt update
          sudo apt install -y gcc-12 g++-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 60

      - name: Install dependencies
        working-directory: ./etl-pipeline
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt

      - name: Run API tests
        working-directory: ./etl-pipeline
        run: |
          pytest tests/integration/api --env=qa
