name: Playwright Tests for DRB Web

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL for environment"
        default: "http://local.nypl.org:3000/"
        required: false
        type: string
      api_url:
        description: "API URL for environment"
        default: "https://drb-api-qa.nypl.org"
        required: false
        type: string

  workflow_call:
    inputs:
      base_url:
        description: "Base URL for environment"
        default: "http://local.nypl.org:3000/"
        required: false
        type: string
      api_url:
        description: "API URL for environment"
        default: "https://drb-api-qa.nypl.org"
        required: false
        type: string

jobs:
  tests:
    name: Run Playwright Tests for DRB Web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "web/.nvmrc"
          cache: npm
          cache-dependency-path: "web/package-lock.json"

      - name: Set environment variables
        working-directory: ./web
        run: |
          touch .env
          printf "BASE_URL=%s\n" "${{ inputs.base_url }}" >> .env
          printf "API_URL=%s\n" "${{ inputs.api_url }}" >> .env
          printf "API_KEY=%s\n" "${{ secrets.API_KEY }}" >> .env
          printf "VRA_USERNAME=%s\n" "${{ secrets.VRA_USERNAME }}" >> .env
          printf "VRA_PASSWORD=%s\n" "${{ secrets.VRA_PASSWORD }}" >> .env
          printf "CATALOG_USERNAME=%s\n" "${{ secrets.CATALOG_USERNAME }}" >> .env
          printf "CATALOG_USER_PIN=%s\n" "${{ secrets.CATALOG_USER_PIN }}" >> .env
        shell: bash

      - name: Add hosts to /etc/hosts
        if: inputs.base_url == 'http://local.nypl.org:3000/'
        run: |
          sudo echo "127.0.0.1 local.nypl.org" | sudo tee -a /etc/hosts

      - name: Install Test Dependencies
        working-directory: ./web
        run: npm i @playwright/test@1.52.0

      - name: Install Playwright
        working-directory: ./web
        run: npx playwright install --with-deps

      - name: Build app
        working-directory: ./web
        run: NODE_ENV=test npm run build

      - name: Start the app
        if: inputs.base_url == 'http://local.nypl.org:3000/'
        working-directory: ./web
        run: |
          NODE_ENV=test npm start &
          sleep 5
        shell: bash

      - name: Run Playwright tests
        working-directory: ./web
        run: npm run playwright
