name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL for environment"
        default: "http://local.nypl.org:3000/"
        required: false
        type: string
      api_url:
        description: "API URL for environment"
        default: "https://drb-api-qa.nypl.org"
        required: false
        type: string
  workflow_call:
    inputs:
      base_url:
        description: "Base URL for environment"
        default: "http://local.nypl.org:3000/"
        required: false
        type: string
      api_url:
        description: "API URL for environment"
        default: "https://drb-api-qa.nypl.org"
        required: false
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  playwright_tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: "web/.nvmrc"
          cache: npm
          cache-dependency-path: "web/package-lock.json"

      - name: Configure AWS credentials for fetching VRA secrets from SSM
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::946183545209:role/GithubActionsDeployerRole
          aws-region: us-east-1

      - name: Fetch API key and HTTP Basic Auth creds for VRA from SSM
        shell: bash
        run: |
          set -euo pipefail
          echo "API_KEY=$(aws ssm get-parameter --name '/drb/qa/api-key' --with-decryption --query 'Parameter.Value' --output text)" >> "$GITHUB_ENV"
          echo "VRA_USERNAME=$(aws ssm get-parameter --name '/drb/qa/vra-test-user/user' --with-decryption --query 'Parameter.Value' --output text)" >> "$GITHUB_ENV"
          echo "VRA_PASSWORD=$(aws ssm get-parameter --name '/drb/qa/vra-test-user/pswd' --with-decryption --query 'Parameter.Value' --output text)" >> "$GITHUB_ENV"

      - name: Set environment for branch
        working-directory: ./web
        run: |
          touch .env
          echo "BASE_URL=${{ inputs.base_url }}" >> .env
          echo "API_URL=${{ inputs.api_url }}" >> .env
          echo "API_KEY=$API_KEY" >> .env
        shell: bash

      - name: Add hosts to /etc/hosts
        if: inputs.base_url == 'http://local.nypl.org:3000/'
        run: |
          sudo echo "127.0.0.1 local.nypl.org" | sudo tee -a /etc/hosts

      - name: Install Test Dependencies
        working-directory: ./web
        run: npm i @playwright/test@1.52.0

      - name: Install Playwright
        working-directory: ./web
        run: npx playwright install --with-deps

      - name: Build app
        working-directory: ./web
        run: NODE_ENV=test npm run build

      - name: Start the app
        if: inputs.base_url == 'http://local.nypl.org:3000/'
        working-directory: ./web
        run: |
          NODE_ENV=test npm start &
          sleep 5
        shell: bash

      - name: Run Playwright tests (DRB)
        working-directory: ./web
        run: npm run playwright:drb
        env:
          CATALOG_USERNAME: ${{ secrets.CATALOG_USERNAME }}
          CATALOG_USER_PIN: ${{ secrets.CATALOG_USER_PIN }}

      - name: Run Playwright tests (VRA)
        if: always()
        working-directory: ./web
        run: npm run playwright:vra
        env:
          VRA_USERNAME: ${{ env.VRA_USERNAME }}
          VRA_PASSWORD: ${{ env.VRA_PASSWORD }}
