name: 'ETL Pipeline Tests (Self-Hosted)'

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'api/**'
      - 'managers/**'
      - 'mappings/**'
      - 'model/**'
      - 'processes/**'
      - 'services/**'
      - 'tests/**'
      - 'utils/**'
      - 'dev-requirements.txt'
      - 'requirements.txt'
      - 'main.py'
      - 'Makefile'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  PRIMARY_AWS_ACCOUNTID: "491147561046"
  SECONDARY_AWS_ACCOUNTID: "946183545209"
  IMAGE_TAG: nypl-nginx-test
  ENVIRONMENT: qa
  # Service credentials
  NYPL_BIB_USER: ${{ secrets.NYPL_BIB_USER }}
  NYPL_BIB_PASSWORD: ${{ secrets.NYPL_BIB_PASSWORD }}
  GITHUB_API_KEY: ${{ secrets.GITHUB_API_KEY }}
  OCLC_WSKEY: ${{ secrets.OCLC_WSKEY }}
  OCLC_SECRET: ${{ secrets.OCLC_SECRET }}
  # AWS service parameters
  ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST }}
  ELASTICSEARCH_INDEX: ${{ secrets.ELASTICSEARCH_INDEX }}
  ELASTICSEARCH_PORT: ${{ secrets.ELASTICSEARCH_PORT }}
  ELASTICSEARCH_SCHEME: ${{ secrets.ELASTICSEARCH_SCHEME }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}

jobs:
  run-tests:
    runs-on: self-hosted
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Primary account credentials
      - name: Configure primary AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.PRIMARY_AWS_ACCOUNTID }}:role/GithubActionsRunnerRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHAPrimarySession-${{ github.run_id }}
          audience: sts.amazonaws.com

      # Secondary account credentials
      - name: Configure cross-account AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.SECONDARY_AWS_ACCOUNTID }}:role/GHACrossAccountRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHASecondarySession-${{ github.run_id }}
          role-chaining: true
          role-duration-seconds: 1800
          audience: sts.amazonaws.com

      - name: Verify AWS access
        run: |
          aws sts get-caller-identity

      # Python environment setup
      - name: Install Python 3.9 and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3.9 python3.9-venv python3.9-dev \
            build-essential cmake libblas-dev liblapack-dev
          sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
          python3 -m pip install --upgrade pip wheel setuptools
          pip install pytest-rerunfailures  # Required for retry functionality
          pip install -r requirements.txt -r dev-requirements.txt

      # FastText installation if needed
      - name: Handle fasttext
        run: |
          pip install --no-cache-dir --force-reinstall \
            --global-option=build_ext \
            --global-option="-I/usr/include" \
            fasttext==0.9.2

      # Test execution
      - name: Run Integration Tests
        run: |
          python3 -m pytest tests/integration \
            --reruns=3 \
            --reruns-delay=5

      - name: Run Functional Tests
        run: |
          python3 -m pytest tests/functional -v

      - name: Cleanup credentials
        run: |
          unset GITHUB_API_KEY
          unset AWS_ACCESS_KEY_ID
          unset AWS_SECRET_ACCESS_KEY
          unset AWS_SESSION_TOKEN