name: Self-Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Print message
        run: echo "Hello from self-hosted runner"

      - name: Check runner details
        run: uname -a && whoami

      - name: List directory contents
        run: ls -lah
