name: QA Environment Tests (Self-Hosted)
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "tests/**"
      - "services/**"
      - "docker-compose.yml"
      - "Dockerfile"
      - "requirements.txt"

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNTID: "491147561046"
  IMAGE_TAG: nypl-nginx-test
  ENVIRONMENT: qa

permissions:
  id-token: write
  contents: read

jobs:
  qa-tests:
    name: QA Integration Tests
    runs-on: self-hosted
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNTID }}:role/GithubActionsRunnerRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHARunnerSession

      - name: Install complete build toolchain
        run: |
          # Ubuntu/Debian
          if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              cmake \
              git \
              autoconf \
              automake \
              libtool \
              pkg-config \
              python3-dev \
              libffi-dev \
              zlib1g-dev \
              libssl-dev
          # RHEL/CentOS
          elif command -v dnf >/dev/null 2>&1; then
            sudo dnf groupinstall -y "Development Tools"
            sudo dnf install -y \
              cmake \
              git \
              autoconf \
              automake \
              libtool \
              pkgconfig \
              python3-devel \
              libffi-devel \
              zlib-devel \
              openssl-devel
          elif command -v yum >/dev/null 2>&1; then
            sudo yum groupinstall -y "Development Tools"
            sudo yum install -y \
              cmake \
              git \
              autoconf \
              automake \
              libtool \
              pkgconfig \
              python3-devel \
              libffi-devel \
              zlib-devel \
              openssl-devel
          fi

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            dev-requirements.txt

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install Python dependencies (with retries)
        run: |
          python -m pip install --upgrade pip wheel setuptools
          # First try installing with pre-built wheels
          pip install --prefer-binary -r requirements.txt || \
          # If that fails, try building from source
          (echo "Falling back to source builds..." && \
           pip install -r requirements.txt)
          
          # Special handling for problematic packages
          pip install --no-cache-dir --force-reinstall \
            --global-option=build_ext \
            --global-option="-I/usr/include" \
            fasttext

      - name: Verify installations
        run: |
          python -m pytest --version
          python -c "import fasttext; print(f'fasttext version: {fasttext.__version__}')"

      - name: Run QA integration tests
        run: |
          python -m pytest tests/integration --env=qa