name: QA Environment Tests (Self-Hosted)
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "tests/**"
      - "services/**"
      - "docker-compose.yml"
      - "Dockerfile"
      - "requirements.txt"

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNTID: "491147561046"
  IMAGE_TAG: nypl-nginx-test
  ENVIRONMENT: qa

permissions:
  id-token: write
  contents: read

jobs:
  qa-tests:
    name: QA Integration Tests
    runs-on: self-hosted
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNTID }}:role/GithubActionsRunnerRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHARunnerSession

      - name: Install Python 3.9 and dependencies
        run: |
          # Ubuntu/Debian
          if command -v apt-get >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install -y python3.9 python3.9-venv
            sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
            sudo update-alternatives --set python3 /usr/bin/python3.9
          
          # Amazon Linux/RHEL
          elif command -v dnf >/dev/null 2>&1; then
            sudo dnf install -y python39 python39-pip
            sudo alternatives --set python3 /usr/bin/python3.9
          
          # CentOS
          elif command -v yum >/dev/null 2>&1; then
            sudo yum install -y python39 python39-pip
            sudo alternatives --set python3 /usr/bin/python3.9
          fi
          
          python3 --version
          python3 -m ensurepip --upgrade
          python3 -m pip install --upgrade pip wheel

      - name: Install test dependencies
        run: |
          python3 -m pip install -r requirements.txt
          python3 -m pip install pytest  # Explicitly install pytest
          python3 -m pytest --version    # Verify installation

      - name: Run QA integration tests
        run: |
          python3 -m pytest tests/integration --env=qa