name: QA Self-Hosted Runner Test
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "api/**"
      - "tests/**"
      - "services/**"
      - "requirements.txt"
      - "dev-requirements.txt"
      - "docker-compose.yml"

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNTID: "491147561046"
  ENVIRONMENT: qa

permissions:
  id-token: write
  contents: read

jobs:
  qa-self-hosted-tests:
    name: Run QA Tests (Self-Hosted)
    runs-on: self-hosted
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNTID }}:role/GithubActionsRunnerRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-12 g++-12
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 60

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt

      - name: Start Docker services
        run: docker compose up -d

      - name: Wait for services
        run: sleep 90

      - name: Run functional tests
        run: make functional

      - name: Run integration tests
        run: make integration

      - name: Cleanup Docker
        if: always()
        run: docker compose down

      - name: Verify AWS access
        run: aws sts get-caller-identity
