name: 'ETL Pipeline Tests (Self-Hosted)'

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'api/**'
      - 'managers/**'
      - 'mappings/**'
      - 'model/**'
      - 'processes/**'
      - 'services/**'
      - 'tests/**'
      - 'utils/**'
      - 'dev-requirements.txt'
      - 'requirements.txt'
      - 'main.py'
      - 'Makefile'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNTID: "491147561046"

jobs:
  run-tests:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNTID }}:role/GithubActionsRunnerRole
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GHARunnerSession-${{ github.run_id }}

      - name: Verify AWS access
        run: aws sts get-caller-identity

    
      - name: Install system dependencies
        run: |
          sudo dnf groupinstall -y "Development Tools"
          sudo dnf install -y python39 python39-devel openssl-devel
          sudo alternatives --set python3 /usr/bin/python3.9

      - name: Set up Python environment
        run: |
          python3 -m pip install --upgrade pip wheel
          pip3 install -r dev-requirements.txt
          pip3 install -r requirements.txt

      - name: Run integration tests
        env:
          ELASTICSEARCH_HOST: ${{ secrets.ELASTICSEARCH_HOST }}
          ELASTICSEARCH_INDEX: ${{ secrets.ELASTICSEARCH_INDEX }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
        run: |
          pytest tests/integration --env=qa