name: ETL_Pipeline_Tests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  changelog:
    name: Updates Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dangoslen/changelog-enforcer@v1.4.0
        with:
          changeLogPath: "CHANGELOG.md"
          skipLabel: "no-changelog"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install allure-pytest
      - name: Run test suite
        run: |
          python -m pytest --alluredir=./allure/allure-results ./tests
      - name: Check for allure results
        run: |
          cd allure/allure-results
          ls
          cd ../..
      - name: Check for allure command
        run: |
          python -m allure --version
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: build/allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
