name: ETL Pipeline Tests (Pull Request)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "api/**"
      - "managers/**"
      - "mappings/**"
      - "model/**"
      - "processes/**"
      - "services/**"
      - "tests/**"
      - "dev-requirements.txt"
      - "requirements.txt"
      - "main.py"
      - "Makefile"

jobs:
  docker-setup:
    name: Start Docker Containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Docker containers
        run: docker compose up -d
      - name: Wait for services to be ready
        run: sleep 90

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      IS_CI: "true"
      AWS_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: local
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install pytest-parallel
      - name: Run Unit Tests
        run: pytest tests/unit --workers 4 -v

  functional-tests:
    name: Functional Tests
    needs: docker-setup
    runs-on: ubuntu-latest
    env:
      IS_CI: "true"
      AWS_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: local
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install pytest-parallel
      - name: Run Functional Tests
        run: pytest tests/functional --workers 2 -v

  integration-tests:
    name: Integration Tests
    needs: docker-setup
    runs-on: ubuntu-latest
    env:
      IS_CI: "true"
      AWS_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: local
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install pytest-parallel
      - name: Run Integration Tests
        run: pytest tests/integration --workers 2 -v

  docker-cleanup:
    name: Stop Docker Containers
    needs: [functional-tests, integration-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Stop Docker containers
        run: docker compose down
