name: ETL Pipeline Tests (Pull Request)

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "api/**"
      - "managers/**"
      - "mappings/**"
      - "model/**"
      - "processes/**"
      - "services/**"
      - "tests/**"
      - "dev-requirements.txt"
      - "requirements.txt"
      - "main.py"
      - "Makefile"

jobs:
  docker-setup:
    name: Start Docker Containers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Docker containers
        run: docker-compose -f docker-compose.yml up -d
      - name: Wait for services to be ready
        run: sleep 90
      - name: Verify running containers
        run: docker ps

  unit-tests:
    name: Unit Tests (Group ${{ matrix.group }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2]
    env:
      IS_CI: "true"
      AWS_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: local
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
      - name: Install pytest-split
        run: pip install pytest-split
      - name: Run Unit Tests (Group ${{ matrix.group }})
        run: |
          pytest tests/unit \
            --splits ${{ strategy.job-total }} \
            --group ${{ matrix.group }} \
            -v || pytest tests/unit -v

  functional-tests:
    name: Functional Tests (Group ${{ matrix.group }})
    needs: docker-setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2]
    env:
      IS_CI: "true"
      AWS_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: local
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
      - name: Install pytest-split
        run: pip install pytest-split
      - name: Run Functional Tests (Group ${{ matrix.group }})
        run: |
          pytest tests/functional \
            --splits ${{ strategy.job-total }} \
            --group ${{ matrix.group }} \
            -v || pytest tests/functional -v

  integration-tests:
    name: Integration Tests (Group ${{ matrix.group }})
    needs: docker-setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        group: [1, 2]
    env:
      IS_CI: "true"
      AWS_ACCESS: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ENVIRONMENT: local
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
      - name: Install pytest-split
        run: pip install pytest-split
      - name: Run Integration Tests (Group ${{ matrix.group }})
        run: |
          pytest tests/integration \
            --splits ${{ strategy.job-total }} \
            --group ${{ matrix.group }} \
            -v || pytest tests/integration -v

  docker-cleanup:
    name: Stop Docker Containers
    needs: [functional-tests, integration-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Stop Docker containers
        run: docker-compose -f docker-compose.yml down
