name: ETL_Pipeline_Tests

on: 
  pull_request:
    actions: [ opened ]
  schedule:
    - cron:  '0 0 * * 1'

jobs:
  changelog:
    name: Updates Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dangoslen/changelog-enforcer@v1.4.0
        with:
          changeLogPath: "CHANGELOG.md"
          skipLabel: "no-changelog"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
          pip install -r requirements.txt
          pip install allure-pytest
      - name: Run test suite
        run: |
          python -m pytest --alluredir=./allure/allure-results ./tests
      - name: Check for allure results
        run: |
          ls
          cd allure_results
      - name: Check for allure command
        run: |
          python -m allure --version
      - name: Generate allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure/allure-results
          allure_report: allure/allure-report
